# Make a discord bot and place token here
discord-token: token here

# To get your channel id, turn on developer mode in settings -> appearance -> Developer Mode
# Right Click on the channel and copy channel ID
discord-channel-id: id here

use-chat-listener: true
use-player-activity-listener: true
