# More info about this config file can be found on the discord @ PLACE DISCORD LINK HERE
discord-token: PASTE YOUR BOT TOKEN HERE
discord-channel-name: CHANNEL NAME
discord-channel-index: 0
use-chat-listener: true
use-player-activity-listener: true
