{
  "commands": {
    "meerchat-reload": {
      "usage": "/meerchat-reload", 
      "description": "Controls the Meerchat plugin."
    }
  }, 
  "version": 0.1,
  "name": "MeerChat", 
  "author": "Maxwell Wenger and Ethan Green", 
  "main": "net.seasharp.meerchat.Main", 
  "description": "Shared chat between Minecraft and Discord"
}