discord-token: 'REPLACE THIS'
discord-channel-name: 'REPLACE THIS'
use-chat-listener: true
use-player-join-listener: true
use-player-leave-listener: true

# Use this if you are referencing a channel with the same name
# Default is 0
discord-channel-index: 0

commands:
  meerchat:
    description: Controls the Meerchat plugin.
    usage: /meerchat
